// HexLab server — server-side project storage.
//
// Projects used to live only in the browser's localStorage, which meant a
// diagram was stuck to one machine/browser. This server persists the same
// data (the project index + each project's full JSON blob) to disk instead,
// so the frontend can be opened from any machine and see the same projects.
//
// Deliberately dependency-free (uses only Node's built-in `http`/`fs`) so it
// runs with nothing more than `node server/index.js` — no `npm install`
// required just to get storage working.
//
// Run: node server/index.js   (defaults to http://localhost:4173)
// In dev, `npm run dev` proxies /api/* here automatically (see vite.config.js).
// In prod, this same server also serves the built dist/ folder if present,
// so `npm run build && npm run server` is a complete, single-process deploy.

const http = require('http');
const fs = require('fs');
const path = require('path');

const PORT = process.env.PORT || 4173;
// Data lives in a top-level UserData/ folder (project root), not inside
// server/ — keeps persisted user data clearly separate from app code, so it
// isn't mistaken for build output and doesn't get wiped by a code redeploy.
const DATA_DIR = path.join(__dirname, '..', 'UserData');
const PROJECTS_DIR = path.join(DATA_DIR, 'projects');
const INDEX_FILE = path.join(DATA_DIR, 'index.json');
const DIST_DIR = path.join(__dirname, '..', 'dist');

fs.mkdirSync(PROJECTS_DIR, { recursive: true });
if (!fs.existsSync(INDEX_FILE)) {
  fs.writeFileSync(INDEX_FILE, JSON.stringify({ activeId: null, projects: [] }, null, 2));
}

function safeId(id) {
  // Project ids are generated by the frontend (genId('proj')) — this is just
  // a defensive check so a crafted id can't be used for path traversal.
  return /^[a-zA-Z0-9_-]+$/.test(id) ? id : null;
}

function sendJson(res, status, data) {
  const body = JSON.stringify(data);
  res.writeHead(status, {
    'Content-Type': 'application/json',
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Methods': 'GET,PUT,POST,DELETE,OPTIONS',
    'Access-Control-Allow-Headers': 'Content-Type',
  });
  res.end(body);
}

function readBody(req) {
  return new Promise((resolve, reject) => {
    let chunks = '';
    req.on('data', (c) => { chunks += c; if (chunks.length > 25 * 1024 * 1024) req.destroy(); });
    req.on('end', () => resolve(chunks));
    req.on('error', reject);
  });
}

const MIME = { '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css', '.json': 'application/json', '.svg': 'image/svg+xml', '.png': 'image/png' };

function serveStatic(req, res) {
  if (!fs.existsSync(DIST_DIR)) { sendJson(res, 404, { error: 'not built — run `npm run build`, or use `npm run dev` for local development' }); return; }
  let filePath = path.join(DIST_DIR, decodeURIComponent(req.url.split('?')[0]));
  if (req.url === '/' || !fs.existsSync(filePath) || fs.statSync(filePath).isDirectory()) {
    filePath = path.join(DIST_DIR, 'index.html');
  }
  fs.readFile(filePath, (err, data) => {
    if (err) { res.writeHead(404); res.end('Not found'); return; }
    res.writeHead(200, { 'Content-Type': MIME[path.extname(filePath)] || 'application/octet-stream' });
    res.end(data);
  });
}

const server = http.createServer(async (req, res) => {
  const url = req.url.split('?')[0];

  if (req.method === 'OPTIONS') { sendJson(res, 204, {}); return; }

  try {
    // ---- Project index: { activeId, projects: [{id,name,createdAt}] } ----
    if (url === '/api/index' && req.method === 'GET') {
      const raw = fs.readFileSync(INDEX_FILE, 'utf8');
      sendJson(res, 200, JSON.parse(raw));
      return;
    }
    if (url === '/api/index' && req.method === 'PUT') {
      const body = JSON.parse(await readBody(req));
      fs.writeFileSync(INDEX_FILE, JSON.stringify(body, null, 2));
      sendJson(res, 200, { ok: true });
      return;
    }

    // ---- Individual project blobs: /api/projects/:id ----
    const projMatch = url.match(/^\/api\/projects\/([^/]+)$/);
    if (projMatch) {
      const id = safeId(decodeURIComponent(projMatch[1]));
      if (!id) { sendJson(res, 400, { error: 'invalid project id' }); return; }
      const file = path.join(PROJECTS_DIR, `${id}.json`);
      if (req.method === 'GET') {
        if (!fs.existsSync(file)) { sendJson(res, 200, {}); return; }
        sendJson(res, 200, JSON.parse(fs.readFileSync(file, 'utf8')));
        return;
      }
      if (req.method === 'PUT') {
        const body = await readBody(req);
        fs.writeFileSync(file, body);
        sendJson(res, 200, { ok: true });
        return;
      }
      if (req.method === 'DELETE') {
        if (fs.existsSync(file)) fs.unlinkSync(file);
        sendJson(res, 200, { ok: true });
        return;
      }
    }

    if (url.startsWith('/api/')) { sendJson(res, 404, { error: 'not found' }); return; }

    // Anything else: serve the built frontend, if present.
    serveStatic(req, res);
  } catch (e) {
    sendJson(res, 500, { error: String(e?.message || e) });
  }
});

server.listen(PORT, () => {
  console.log(`HexLab server storage listening on http://localhost:${PORT}`);
  console.log(`Project data is stored in ${DATA_DIR}`);
});
